### Отбор, блокировка и завершение задачи Открыть регистрацию

GET {{url}}/engine-rest/external-task?processInstanceId={{processInstanceId}}&topic-name=end


### fetchAndLock

POST {{url}}/engine-rest/external-task/fetchAndLock
Content-Type: application/json

{
  "workerId": "test",
  "maxTasks": 1,
  "topics": [
    {
      "topicName":  "end",
      "lockDuration": 10000
    }
  ]
}

> {%

    client.global.set("taskId", response.body[0].id)

%}

### complete

POST {{url}}/engine-rest/external-task/{{taskId}}/complete
Content-Type: application/json

{
  "workerId": "test"
}
